[phases.setup]
nixPkgs = ["openjdk21"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -jar -Dspring.profiles.active=railway target/vehicle-management-1.0.0.war"

[variables]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "railway"
